CREATE TABLE `PAGE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CODE` VARCHAR(10) DEFAULT NULL,
  `NAME` VARCHAR(100) DEFAULT NULL,
  `PARENTCODE` VARCHAR(10) DEFAULT NULL,
  `LEVEL` INT DEFAULT NULL,
  `URL` VARCHAR(500) DEFAULT NULL,
  `HIDDEN` INT DEFAULT NULL,
  `ICON` VARCHAR(50) DEFAULT NULL,
  `SORT` INT DEFAULT NULL,
  `CREATEDTIME` DATETIME DEFAULT NULL,
  `CREATEDBY` VARCHAR(16) DEFAULT NULL,
  `UPDATEDTIME` DATETIME DEFAULT NULL,
  `UPDATEDBY` VARCHAR(16) DEFAULT NULL,
  `DELETEDBY` VARCHAR(16) DEFAULT NULL,
  `DELETEDFLAG` INT NOT NULL DEFAULT '0',
  `DELETEDTIME` DATETIME DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;

CREATE TABLE `ROLE` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `CODE` varchar(10) DEFAULT NULL,
  `NAME` varchar(100) DEFAULT NULL COMMENT 'role name',
  `CREATEDTIME` datetime DEFAULT NULL,
  `CREATEDBY` varchar(16) DEFAULT NULL,
  `UPDATEDTIME` datetime DEFAULT NULL,
  `UPDATEDBY` varchar(16) DEFAULT NULL,
  `DELETEDBY` varchar(16) DEFAULT NULL,
  `DELETEDFLAG` int NOT NULL DEFAULT '0',
  `DELETEDTIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `PAGE_ROLE` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `PAGECODE` varchar(10) DEFAULT NULL,
  `ROLECODE` varchar(10) DEFAULT NULL,
  `CREATEDTIME` datetime DEFAULT NULL,
  `CREATEDBY` varchar(16) DEFAULT NULL,
  `UPDATEDTIME` datetime DEFAULT NULL,
  `UPDATEDBY` varchar(16) DEFAULT NULL,
  `DELETEDBY` varchar(16) DEFAULT NULL,
  `DELETEDFLAG` int NOT NULL DEFAULT '0',
  `DELETEDTIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='relationship between page and role';


CREATE TABLE `USER_ROLE` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `USERID` int NOT NULL,
  `ROLECODE` varchar(10) DEFAULT NULL,
  `CREATEDTIME` datetime DEFAULT NULL,
  `CREATEDBY` varchar(16) DEFAULT NULL,
  `UPDATEDTIME` datetime DEFAULT NULL,
  `UPDATEDBY` varchar(16) DEFAULT NULL,
  `DELETEDBY` varchar(16) DEFAULT NULL,
  `DELETEDFLAG` int NOT NULL DEFAULT '0',
  `DELETEDTIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDBD DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='relationship between user and role';