create database demo;
use demo;

CREATE TABLE `AUTH_USER` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(20) NOT NULL,
  `PASSWORD` varchar(100) NOT NULL,
  `FULLNAME` varchar(100) DEFAULT NULL,
  `EMAIL` varchar(100) DEFAULT NULL,
  `FIRSTLOGIN` int DEFAULT NULL COMMENT '0: not yet login\\n1: logined',
  `INDATE` varchar(8) DEFAULT NULL,
  `OUTDATE` varchar(8) DEFAULT NULL,
  `FAILCOUNT` int DEFAULT NULL COMMENT 'count times loging fail, if loging fail 5 time lock account',
  `ISLOCKED` int NOT NULL DEFAULT '0' COMMENT '0: no lock, 1: locked',
  `AVATAR` varchar(500) DEFAULT NULL COMMENT 'link avata image',
  `LASTLOGIN` datetime DEFAULT NULL,
  `CREATEDTIME` datetime DEFAULT NULL,
  `CREATEDBY` varchar(20) DEFAULT NULL,
  `UPDATEDTIME` datetime DEFAULT NULL,
  `UPDATEDBY` varchar(20) DEFAULT NULL,
  `DELETEDBY` varchar(20) DEFAULT NULL,
  `DELETEDFLAG` int NOT NULL DEFAULT '0',
  `DELETEDTIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='User table';

CREATE TABLE `AUTH_PAGE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CODE` VARCHAR(10) DEFAULT NULL,
  `NAME` VARCHAR(100) DEFAULT NULL,
  `PARENTCODE` VARCHAR(10) DEFAULT NULL,
  `LEVEL` INT DEFAULT NULL,
  `URL` VARCHAR(500) DEFAULT NULL,
  `HIDDEN` INT DEFAULT NULL,
  `ICON` VARCHAR(50) DEFAULT NULL,
  `SORT` INT DEFAULT NULL,
  `CREATEDTIME` DATETIME DEFAULT NULL,
  `CREATEDBY` VARCHAR(16) DEFAULT NULL,
  `UPDATEDTIME` DATETIME DEFAULT NULL,
  `UPDATEDBY` VARCHAR(16) DEFAULT NULL,
  `DELETEDBY` VARCHAR(16) DEFAULT NULL,
  `DELETEDFLAG` INT NOT NULL DEFAULT '0',
  `DELETEDTIME` DATETIME DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;

CREATE TABLE `AUTH_ROLE` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `CODE` varchar(50) DEFAULT NULL,
  `NAME` varchar(100) DEFAULT NULL COMMENT 'role name',
  `CREATEDTIME` datetime DEFAULT NULL,
  `CREATEDBY` varchar(16) DEFAULT NULL,
  `UPDATEDTIME` datetime DEFAULT NULL,
  `UPDATEDBY` varchar(16) DEFAULT NULL,
  `DELETEDBY` varchar(16) DEFAULT NULL,
  `DELETEDFLAG` int NOT NULL DEFAULT '0',
  `DELETEDTIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `AUTH_PAGE_ROLE` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `PAGECODE` varchar(10) DEFAULT NULL,
  `ROLECODE` varchar(10) DEFAULT NULL,
  `CREATEDTIME` datetime DEFAULT NULL,
  `CREATEDBY` varchar(16) DEFAULT NULL,
  `UPDATEDTIME` datetime DEFAULT NULL,
  `UPDATEDBY` varchar(16) DEFAULT NULL,
  `DELETEDBY` varchar(16) DEFAULT NULL,
  `DELETEDFLAG` int NOT NULL DEFAULT '0',
  `DELETEDTIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='relationship between page and role';


CREATE TABLE `AUTH_USER_ROLE` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `USERID` int NOT NULL,
  `ROLECODE` varchar(50) DEFAULT NULL,
  `CREATEDTIME` datetime DEFAULT NULL,
  `CREATEDBY` varchar(16) DEFAULT NULL,
  `UPDATEDTIME` datetime DEFAULT NULL,
  `UPDATEDBY` varchar(16) DEFAULT NULL,
  `DELETEDBY` varchar(16) DEFAULT NULL,
  `DELETEDFLAG` int NOT NULL DEFAULT '0',
  `DELETEDTIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='relationship between user and role';

CREATE TABLE `AUTH_ACTION` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) DEFAULT NULL,
  `ACTIONCODE` varchar(10) DEFAULT NULL,
  `CREATEDTIME` datetime DEFAULT NULL,
  `CREATEDBY` varchar(16) DEFAULT NULL,
  `UPDATEDTIME` datetime DEFAULT NULL,
  `UPDATEDBY` varchar(16) DEFAULT NULL,
  `DELETEDBY` varchar(16) DEFAULT NULL,
  `DELETEDFLAG` int NOT NULL DEFAULT '0',
  `DELETEDTIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `AUTH_PAGE_ACTION` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `PAGECODE` varchar(10) DEFAULT NULL,
  `ACTIONCODE` varchar(10) DEFAULT NULL,
  `CREATEDTIME` datetime DEFAULT NULL,
  `CREATEDBY` varchar(16) DEFAULT NULL,
  `UPDATEDTIME` datetime DEFAULT NULL,
  `UPDATEDBY` varchar(16) DEFAULT NULL,
  `DELETEDBY` varchar(16) DEFAULT NULL,
  `DELETEDFLAG` int NOT NULL DEFAULT '0',
  `DELETEDTIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='relationship between page and action';


CREATE TABLE `AUTH_PAGE_ACTION_ROLE` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `PAGECODE` varchar(10) DEFAULT NULL,
  `ACTIONCODE` varchar(10) DEFAULT NULL,
  `ROLECODE` varchar(10) DEFAULT NULL,
  `CREATEDTIME` datetime DEFAULT NULL,
  `CREATEDBY` varchar(16) DEFAULT NULL,
  `UPDATEDTIME` datetime DEFAULT NULL,
  `UPDATEDBY` varchar(16) DEFAULT NULL,
  `DELETEDBY` varchar(16) DEFAULT NULL,
  `DELETEDFLAG` int NOT NULL DEFAULT '0',
  `DELETEDTIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `AUTH_ORDERS` (
	`ID` INT NOT NULL AUTO_INCREMENT,
    `USERID` INT NOT NULL,
    `SHIPPINGADDRESS` VARCHAR(100) DEFAULT NULL,
    `TOTAL` DECIMAL(15,2) NOT NULL DEFAULT '0',
    `STATUS` INT NOT NULL DEFAULT '0',
    `PAYMENTMETHOD` VARCHAR(20) DEFAULT NULL,
    `PAYMENTEDTIME` DATETIME DEFAULT NULL,
    `PAYMENTEDBY` VARCHAR(10) DEFAULT NULL,
    `CREATEDTIME` DATETIME DEFAULT NULL,
    `CREATEDBY` VARCHAR(10) DEFAULT NULL,
    `UPDATEDTIME` DATETIME DEFAULT NULL,
    `UPDATEDBY` VARCHAR(10) DEFAULT NULL,
    `DELETEDTIME` DATETIME DEFAULT NULL,
    `DELETEDBY` VARCHAR(10) DEFAULT NULL,
    `DELETEDFLAG` INT NOT NULL DEFAULT '0',
    PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;

CREATE TABLE `AUTH_ORDERDETAIL` (
	`ID` INT NOT NULL AUTO_INCREMENT,
    `ORDERID` INT NOT NULL,
    `PRODUCTID` INT NOT NULL,
    `QUANTITY` INT DEFAULT '0',
    `PRICE` DECIMAL(10,2) NOT NULL DEFAULT '0',
    `TOTAL` DECIMAL(15,2) NOT NULL DEFAULT '0',
    `CREATEDTIME` DATETIME DEFAULT NULL,
    `CREATEDBY` VARCHAR(10) DEFAULT NULL,
    `UPDATEDTIME` DATETIME DEFAULT NULL,
    `UPDATEDBY` VARCHAR(10) DEFAULT NULL,
    `DELETEDTIME` DATETIME DEFAULT NULL,
    `DELETEDBY` VARCHAR(10) DEFAULT NULL,
    `DELETEDFLAG` INT NOT NULL DEFAULT '0',
    PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;

CREATE TABLE `AUTH_PRODUCT` (
	`ID` INT NOT NULL AUTO_INCREMENT,
    `PRODUCTNAME` VARCHAR(100) DEFAULT NULL,
    `DESCRIPTION` VARCHAR(200) DEFAULT NULL,
    `PRICE` DECIMAL(10,2) NOT NULL DEFAULT '0',
    `STOCKQUANTITY` INT NOT NULL DEFAULT '0',
    `CATEGORY` INT NOT NULL,
    `SUPPLIER` VARCHAR(50),
    `CREATEDTIME` DATETIME DEFAULT NULL,
    `CREATEDBY` VARCHAR(10) DEFAULT NULL,
    `UPDATEDTIME` DATETIME DEFAULT NULL,
    `UPDATEDBY` VARCHAR(10) DEFAULT NULL,
    `DELETEDTIME` DATETIME DEFAULT NULL,
    `DELETEDBY` VARCHAR(10) DEFAULT NULL,
    `DELETEDFLAG` INT NOT NULL DEFAULT '0',
    PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;

CREATE TABLE `AUTH_PRODUCT_IMAGE` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `IDPRODUCT` INT NOT NULL,
    `IMAGEURL` VARCHAR(255) NOT NULL,
    `CREATEDTIME` DATETIME DEFAULT NULL,
    `CREATEDBY` VARCHAR(10) DEFAULT NULL,
    `UPDATEDTIME` DATETIME DEFAULT NULL,
    `UPDATEDBY` VARCHAR(10) DEFAULT NULL,
    `DELETEDTIME` DATETIME DEFAULT NULL,
    `DELETEDBY` VARCHAR(10) DEFAULT NULL,
    `DELETEDFLAG` INT NOT NULL DEFAULT '0',
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;

DELIMITER //
CREATE PROCEDURE sp_auth_user_insert(
    IN p_UserName VARCHAR(20),
    IN p_PassWord VARCHAR(100),
    IN p_FullName VARCHAR(100),
    IN p_Email VARCHAR(100),
    IN p_Avatar VARCHAR(500),
    IN p_CreatedBy VARCHAR(20),
    IN p_RoleCode JSON
)
BEGIN
    DECLARE v_UserID INT;

    -- Thêm user vào bảng AUTH_USER
    INSERT INTO AUTH_USER (
        USERNAME, PASSWORD, FULLNAME, EMAIL, AVATAR, CREATEDTIME, CREATEDBY
    ) VALUES (
        p_UserName, p_PassWord, p_FullName, p_Email, p_Avatar, NOW(), p_CreatedBy
    );

    -- Lấy ID của user vừa tạo
    SET v_UserID = LAST_INSERT_ID();

    -- Chèn danh sách role vào bảng AUTH_USER_ROLE từ JSON
    INSERT INTO AUTH_USER_ROLE (USERID, ROLECODE, CREATEDTIME, CREATEDBY)
    SELECT v_UserID, JSON_UNQUOTE(JSON_EXTRACT(Item, '$.Code')) AS ROLECODE, NOW(), p_CreatedBy
    FROM JSON_TABLE(p_RoleCode, '$[*]' COLUMNS (Item JSON PATH '$')) AS Item;

END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE sp_auth_user_selectAll()
BEGIN
    SELECT 
        u.*, 
        COALESCE(
            CONCAT('[', GROUP_CONCAT(
                JSON_OBJECT('code', r.ROLECODE)
            ), ']'), 
            '[]'
        ) AS roleCode
    FROM AUTH_USER u
    LEFT JOIN AUTH_USER_ROLE r ON u.ID = r.USERID
    WHERE u.DELETEDFLAG = 0
    GROUP BY u.ID;
    
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE sp_auth_user_selectByID(IN p_ID INT)
BEGIN
    SELECT 
        u.*, 
        COALESCE(
            CONCAT('[', GROUP_CONCAT(
                JSON_OBJECT('code', r.ROLECODE)
            ), ']'), 
            '[]'
        ) AS roleCode
    FROM AUTH_USER u
    LEFT JOIN AUTH_USER_ROLE r ON u.ID = r.USERID
    WHERE u.ID = p_ID AND u.DELETEDFLAG = 0
    GROUP BY u.ID;
    
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE sp_auth_user_deleteByID(IN p_ID INT, IN p_DeletedBy VARCHAR(20))
BEGIN
    -- Xóa mềm trong bảng AUTH_USER
    UPDATE AUTH_USER
    SET 
        DELETEDFLAG = 1,
        DELETEDTIME = NOW(),
        DELETEDBY = p_DeletedBy
    WHERE ID = p_ID;
    
    -- Xóa mềm trong bảng AUTH_USER_ROLE
    UPDATE AUTH_USER_ROLE
    SET 
        DELETEDFLAG = 1,
        DELETEDTIME = NOW(),
        DELETEDBY = p_DeletedBy
    WHERE USERID = p_ID;
    
END //
DELIMITER ;



